services:
  errbook:
    build:
      context: .
      dockerfile: Dockerfile
    image: errbook:latest
    container_name: errbook
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DATABASE_URL: file:/app/data/dev.db
      UPLOAD_DIR: /app/public/uploads
    expose:
      - "${APP_PORT:-3000}"
    #ports:
    #  - "${APP_PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/public/uploads
    networks:
      - shared-network

networks:
  shared-network:
    external: true
